# Generated by Django 3.2.7 on 2021-09-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio',
            field=models.BooleanField(default=False, verbose_name='adu'),
        ),
    ]
