# Generated by Django 3.2.7 on 2021-09-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210916_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='books',
            new_name='cartItems',
        ),
    ]
