# Generated by Django 3.2.7 on 2021-09-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_books_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
