# Generated by Django 3.2.7 on 2021-09-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210917_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='books',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.book'),
            preserve_default=False,
        ),
    ]
