# Generated by Django 3.2.7 on 2021-09-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_bookrating_bookreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='rating',
            new_name='rates',
        ),
    ]
